[features]
seeds = false
[programs.localnet]
anchor_escrow = "B4YHD52eFecEENwZcrKaA8NX3QSkvQuRa8FrjrcyjutS"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/Users/aoikurokawa/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha  -t 1000000 tests/**/*.ts"
